name: 'Privalyse Security Scan'
description: 'Scan your code for PII leaks, GDPR violations, and AI security risks.'
author: 'Privalyse'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  root:
    description: 'Root directory to scan'
    required: false
    default: '.'
  out:
    description: 'Output file path'
    required: false
    default: 'privalyse_report.md'
  format:
    description: 'Output format (markdown, json, html)'
    required: false
    default: 'markdown'
runs:
  using: "composite"
  steps:
    - name: Install Privalyse
      shell: bash
      run: pip install privalyse-cli

    - name: Run Scan
      shell: bash
      run: privalyse --root ${{ inputs.root }} --out ${{ inputs.out }} --format ${{ inputs.format }}
